{% set name = "PythiaPhyloPredictor" %}
{% set version = "2.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pythiaphylopredictor-{{ version }}.tar.gz
  sha256: 7449450ac27ec783ad103392035de5725e6fa54c65ec655c14b4d4734bb88b05

build:
  entry_points:
    - pythia = pypythia.main:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.9,<3.13
    - hatchling
    - pip
  run:
    - python >=3.9,<3.13
    - pandas
    - biopython
    - lightgbm >=4.4
    - numpy >=2.0
    - shap >=0.41
    - matplotlib-base
    - loguru

test:
  imports:
    - pypythia
    - pypythia.msa
    - pypythia.raxmlng
    - pypythia.prediction
    - pypythia.predictor 
  commands:
    - pip check
    - pythia --help
  requires:
    - pip
    - python >=3.9,<3.13

about:
  summary: Lightweight python library for predicting the difficulty of alignments in phylogenetics
  license: GPL-3.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - tschuelia
  feedstock-name: pypythia
