{% set name = "PyPythia" %}
{% set version = "1.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/tschuelia/PyPythia/archive/{{ version }}.tar.gz
  sha256: 342e3262e00eaa3386ee3c363a71d3244df2a51a99d865dd419d8014a3f4ad72

build:
  entry_points:
    - pythia = pypythia.prediction:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - setuptools
    - wheel
    - pip
  run:
    - python >=3.7
    - pandas
    - biopython
    - scikit-learn >=1.0, < 1.3
    - lightgbm >=3.3, < 4.0.0
    - numpy
    - shap >=0.41
    - matplotlib-base
    - __unix

test:
  imports:
    - pypythia
    - pypythia.msa
    - pypythia.raxmlng
    - pypythia.prediction
    - pypythia.predictor
  commands:
    - pip check
    - pythia --help
  requires:
    - pip

about:
  home: https://github.com/tschuelia/PyPythia
  summary: Lightweight python library for predicting the difficulty of alignments in phylogenetics
  license: GPL-2.0-or-later
  license_file: LICENSE

extra:
  recipe-maintainers:
    - tschuelia
