{% set name = "PyPythia" %}
{% set version = "2.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/tschuelia/PyPythia/archive/{{ version }}.tar.gz
  sha256: 41e3691b0d4d7baf04ea148197758fb2f4c0ada9f9713a2d95b8e7b925f4bba0

build:
  entry_points:
    - pythia = pypythia.prediction:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - wheel
    - pip
  run:
    - python >={{ python_min }}
    - pandas
    - biopython
    - scikit-learn >=1.0, < 1.3
    - lightgbm >=3.3, < 4.0.0
    - numpy
    - shap >=0.41
    - matplotlib-base
    - __unix

test:
  imports:
    - pypythia
    - pypythia.msa
    - pypythia.raxmlng
    - pypythia.prediction
    - pypythia.predictor
  commands:
    - pip check
    - pythia --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/tschuelia/PyPythia
  summary: Lightweight python library for predicting the difficulty of alignments in phylogenetics
  license: GPL-2.0-or-later
  license_file: LICENSE

extra:
  recipe-maintainers:
    - tschuelia
