{% set name = "PyPythia" %}
{% set version = "1.1.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/tschuelia/PyPythia/archive/{{ version }}.tar.gz
  sha256: 9169d5d9d6f21b5330bd30bf0b0f43a30c0e2fcb034e871a9653d2444893fc3e

build:
  entry_points:
    - pythia = pypythia.prediction:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - setuptools
    - wheel
    - pip
  run:
    - python >=3.7
    - pandas
    - biopython
    - scikit-learn >=1.0
    - lightgbm >=3.3
    - numpy
    - shap >=0.41
    - matplotlib
    - __unix

test:
  imports:
    - pypythia
    - pypythia.msa
    - pypythia.raxmlng
    - pypythia.prediction
    - pypythia.predictor
  commands:
    - pip check
    - pythia --help
  requires:
    - pip

about:
  home: https://github.com/tschuelia/PyPythia
  summary: Lightweight python library for predicting the difficulty of alignments in phylogenetics
  license: GPL-2.0-or-later
  license_file: LICENSE

extra:
  recipe-maintainers:
    - tschuelia
